services:
  - type: web
    name: db-stress-framework
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: db-stress-history
          property: host
      - key: DB_PORT
        fromDatabase:
          name: db-stress-history
          property: port
      - key: DB_NAME
        fromDatabase:
          name: db-stress-history
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: db-stress-history
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: db-stress-history
          property: password

databases:
  - name: db-stress-history
    plan: free
