spring.application.name=db-stress-framework
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_stress}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:zeba}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.thymeleaf.cache=false

springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info,metrics

dbstress.target.pool.max-lifetime-ms=1800000
dbstress.target.pool.connection-timeout-ms=10000
dbstress.target.pool.validation-timeout-ms=5000
