package com.zebacodes.dbstress.service.dialect;

import org.springframework.stereotype.Component;

@Component
public class OracleDialect implements DatabaseDialect {

    @Override
    public String name() {
        return "Oracle";
    }

    @Override
    public boolean supports(String jdbcUrl) {
        return jdbcUrl != null && jdbcUrl.startsWith("jdbc:oracle:");
    }

    @Override
    public String createWorkloadTableSql() {
        return """
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE stress_test_data (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        value CLOB NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN
                            RAISE;
                        END IF;
                END;
                """;
    }

    @Override
    public String simpleReadSql() {
        return "SELECT 1 FROM dual";
    }

    @Override
    public String filteredReadSql() {
        return "SELECT id, value FROM stress_test_data WHERE id >= ? ORDER BY id FETCH FIRST 25 ROWS ONLY";
    }

    @Override
    public String aggregateReadSql() {
        return "SELECT count(*), max(updated_at) FROM stress_test_data";
    }

    @Override
    public String insertSql() {
        return "INSERT INTO stress_test_data (value, updated_at) VALUES (?, CURRENT_TIMESTAMP)";
    }

    @Override
    public String updateSql() {
        return "UPDATE stress_test_data SET value = ?, updated_at = CURRENT_TIMESTAMP WHERE id IN (SELECT id FROM stress_test_data ORDER BY id DESC FETCH FIRST 10 ROWS ONLY)";
    }

    @Override
    public String deleteSql() {
        return "DELETE FROM stress_test_data WHERE id IN (SELECT id FROM stress_test_data ORDER BY id ASC FETCH FIRST 1 ROW ONLY)";
    }
}
